import Image from "next/image";

const IMAGES = [
  { file: "1_actual_vs_predicted_all_models.png", title: "Actual vs Predicted", desc: "Comparison of all model predictions against true solar power output." },
  { file: "2_correlation_heatmap.png", title: "Feature Correlation", desc: "Heatmap showing the relationship between weather features and solar output." },
  { file: "3_future_forecast_next_24h.png", title: "24h Future Forecast", desc: "A pure out-of-sample forecast for the next 24 hours." },
  { file: "4_model_comparison_table.png", title: "Metrics Table", desc: "Tabular summary of model performance." },
  { file: "5_model_metrics_bar_chart.png", title: "Metrics Bar Chart", desc: "Visual comparison of MAE and RMSE across all models." },
  { file: "6_raw_time_series_plot.png", title: "Raw Time Series", desc: "The raw dataset showing daily solar cycles and seasonality." },
  { file: "7_recursive_daylight_metrics_bar_chart.png", title: "Daylight Metrics", desc: "Model performance specifically evaluated during daylight hours." },
  { file: "8_residual_plot_error_analysis.png", title: "Residual Error Analysis", desc: "Distribution of prediction errors highlighting model bias." },
  { file: "9_system_architecture_diagram.png", title: "System Architecture", desc: "High-level block diagram of the data engineering and inference pipeline." },
];

export default function ResearchPage() {
  return (
    <div className="page-frame">
      <div className="mb-12">
        <span className="eyebrow">Visualizations</span>
        <h1 className="text-4xl font-bold text-[#1E293B]">Research Gallery</h1>
        <p className="text-slate-600 mt-2 max-w-2xl text-lg">
          Visual outputs generated by the Python data science pipeline during model training and evaluation.
        </p>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        {IMAGES.map((img, i) => (
          <div key={i} className="card-panel p-4 flex flex-col group hover:border-[#1E3A8A] transition-colors">
            <div className="relative h-48 w-full rounded border border-slate-200 overflow-hidden bg-slate-50 mb-4 shadow-sm">
              <Image 
                src={`/research/${img.file}`} 
                alt={img.title}
                fill
                className="object-contain group-hover:scale-105 transition-transform duration-500 p-2"
              />
            </div>
            <h3 className="font-bold text-lg mb-2 text-[#1E293B]">{img.title}</h3>
            <p className="text-slate-600 text-sm flex-1 leading-relaxed">{img.desc}</p>
            <a 
              href={`/research/${img.file}`} 
              target="_blank" 
              className="mt-4 text-[#1E3A8A] text-sm font-semibold hover:text-blue-600"
            >
              View Full Size &rarr;
            </a>
          </div>
        ))}
      </div>
    </div>
  );
}
